import Head from 'next/head'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import dayjs from 'dayjs'
import timezone from 'dayjs/plugin/timezone'
import utc from 'dayjs/plugin/utc'

dayjs.extend(timezone)
dayjs.extend(utc)
dayjs.tz.setDefault('Asia/Tokyo')

const intervalSecond = 30
const formatStyle = 'MM/DD HH:mm:ss'

export default function Home({
  createdAt,
  nextCreatedAt,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div className='container'>
      <Head>
        <title>ISR sample</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <h2>Interval</h2>
        <h1>{intervalSecond}s</h1>
        <br />
        <h2>Page accessed time</h2>
        <h1>{dayjs().tz().format(formatStyle)}</h1>
        <h2>Next HTML can be generated time</h2>
        <h1>{nextCreatedAt}</h1>
        <h2>HTML created time</h2>
        <h1>{createdAt}</h1>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = () => {
  const currentTime = dayjs().tz()
  const createdAt = currentTime.format(formatStyle)
  const nextCreatedAt = currentTime.add(intervalSecond, 's').format(formatStyle)

  return {
    props: {
      createdAt,
      nextCreatedAt,
    },
    revalidate: intervalSecond,
  }
}
